FROM nginx:1.14.1-alpine

LABEL author="Christopher Koleda" version="1.0.0"

# RUN apk update && \
#     mkdir -p /var/www/data && \
#     addgroup -g 1001 -S www-data && \
#     adduser -u 1001 -S www-data -G www-data

ADD nginx.conf /etc/nginx/
ADD laravel.conf /etc/nginx/sites-enabled/default

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    && adduser -D -H -u 1001 -s /bin/bash www-data

ARG PHP_UPSTREAM_CONTAINER=php-fpm
ARG PHP_UPSTREAM_PORT=9000

# Set upstream conf and remove the default conf
RUN echo "upstream php-upstream { server ${PHP_UPSTREAM_CONTAINER}:${PHP_UPSTREAM_PORT}; }" > /etc/nginx/conf.d/upstream.conf \
    && rm /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html

EXPOSE 80 443

CMD nginx